version: '3.8'

volumes:
  postgres14-database:

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres14
    container_name: postgres14
    volumes:
      - postgres14-database:/var/lib/postgresql/data
      - ./backups:/opt/backups
    networks:
      - postgres_conn
    ports:
      - '5442:5432'
    env_file: 
      - .env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: oceanware@gmail.com
      PGADMIN_DEFAULT_PASSWORD: a1128f69-e6f7-4e93-a2df-3d4db6030abc
    ports:
    - "8889:80"
    networks:
    - postgres_conn

networks:
  postgres_conn:
    driver: bridge